name: Website Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
   uses: ./.github/workflows/reusable.yaml
   with:
    artifact_name: "dist-files"
   secrets:
    client_id: ${{secrets.DEVID}}
    client_secrets: ${{secrets.DEVSECRETS}}


  
